jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Debug secrets presence
        run: |
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME is EMPTY";
          else
            echo "DOCKER_USERNAME is SET";
          fi

          if [ -z "$DOCKER_TOKEN" ]; then
            echo "DOCKER_TOKEN is EMPTY";
          else
            echo "DOCKER_TOKEN is SET";
          fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: foosball/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foosball:latest
